version: "3.8"
services:
  db:
    image: postgres:17
    container_name: db_app
    command: -p 2222
    expose:
      - 2222
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_rest
    command: ["/fastapi_rest/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis