services:
  db:
    image: postgres:17
    container_name: db_fastapi_rest
    command: -p 2222
    expose:
      - "2222"
    env_file:
      - .env.prod

  test_db:
    image: postgres:17
    container_name: test_db_fastapi_rest
    command: -p 5433
    expose:
      - "5433"
    env_file:
      - .env.test

  redis:
    image: redis:7
    container_name: redis_fastapi_rest
    command: --port 5370
    expose:
      - "5370"

  app:
    build:
      context: .
    environment:
      - DOCKER_ENV=true
    env_file:
      - .env.prod
    container_name: fastapi_rest
    command: ["/fastapi_rest/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
      - test_db
    volumes:
      - .:/fastapi_rest